runtime: php81
instance_class: F1

automatic_scaling:
    max_instances: 1
    min_instances: 0

handlers:

  - url: .*
    script: auto
    secure: always
    redirect_http_response_code: 301

env_variables:
  ENVIRONMENT: gcp
