name: Deploy

on:
  pull_request:
    branches:
      - main

jobs:

  unit_tests:
    uses: ./.github/workflows/tests_unit.yml
    secrets:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  functional_tests:
    uses: ./.github/workflows/tests_functional.yml
  phpcs:
    uses: ./.github/workflows/phpcs.yml
  phpstan:
    uses: ./.github/workflows/phpstan.yml

  deploy_to_GAE:
    uses: ./.github/workflows/deploy_to_GAE.yml
    secrets:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
    needs:
      - unit_tests
      - functional_tests
      - phpcs
      - phpstan
