name: Tests-Unit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  COMPOSER_ALLOW_SUPERUSER: 1
  COMPOSER_HOME: /composer
  GITHUB_WORKSPACE: /github/workspace/planet-interview-challenge
  ENV: dev

jobs:
  tests-unit:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Fetch data from git
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        working-directory: .
        run: |
          composer install --prefer-dist --no-progress --no-suggest
          composer require --prefer-dist --no-progress --no-suggest --dev php-coveralls/php-coveralls

      - name: Build Tests
        run: |
          vendor/bin/codecept build

      - name: Unit Tests
        run: |
          XDEBUG_MODE=coverage php vendor/bin/codecept run unit --steps --coverage-xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |          
          vendor/bin/php-coveralls --coverage_clover=tests/_output/coverage.xml -v --json_path=tests/_output/coveralls.json

      - uses: AutoModality/action-clean@v1
